import type { ScenarioStructure } from "./localized-types";

/**
 * The structural (non-translatable) shape of every simulator
 * scenario — key, age band, all MinorUnits amounts, and every
 * event/choice's id/type/category. The actual translatable text
 * (titles, descriptions, consequences, choice labels) lives under
 * `simulatorScenarios.<key>` in each locale's messages/*.json — see
 * localized-types.ts.
 *
 * Generated by scripts/migrate-simulator-to-i18n.ts from the
 * original English-only scenario files.
 */
export const SCENARIO_STRUCTURES: ScenarioStructure[] = [
  {
    key: "explorer-standard",
    ageBand: "explorer",
    difficulty: "standard",
    startingBalanceMinorUnits: 0,
    savingsGoalTargetMinorUnits: 2000,
    xpReward: 30,
    coinRewardMinorUnits: 600,
    estimatedMinutes: 4,
    weeks: [
      {
        id: "w1",
        incomeMinorUnits: 1000,
      },
      {
        id: "w2",
        incomeMinorUnits: 1000,
        event: {
          id: "lost-bottle",
          type: "expense",
          costMinorUnits: 300,
        },
      },
      {
        id: "w3",
        incomeMinorUnits: 1000,
        event: {
          id: "game-sale",
          type: "opportunity",
          choices: [
            { key: "buy", category: "wants", costMinorUnits: 600 },
            { key: "skip", category: "wants", costMinorUnits: 0 },
          ],
        },
      },
      {
        id: "w4",
        incomeMinorUnits: 500,
        event: {
          id: "goal-check",
          type: "milestone",
        },
      },
    ],
  },
  {
    key: "explorer-challenge",
    ageBand: "explorer",
    difficulty: "challenge",
    startingBalanceMinorUnits: 200,
    savingsGoalTargetMinorUnits: 3000,
    xpReward: 40,
    coinRewardMinorUnits: 800,
    estimatedMinutes: 5,
    weeks: [
      {
        id: "w1",
        incomeMinorUnits: 1000,
      },
      {
        id: "w2",
        incomeMinorUnits: 1000,
        event: {
          id: "bike-repair",
          type: "expense",
          costMinorUnits: 500,
        },
      },
      {
        id: "w3",
        incomeMinorUnits: 1000,
        event: {
          id: "birthday",
          type: "opportunity",
          choices: [
            { key: "gift", category: "giving", costMinorUnits: 400 },
            { key: "card", category: "giving", costMinorUnits: 0 },
          ],
        },
      },
      {
        id: "w4",
        incomeMinorUnits: 1000,
        event: {
          id: "extra-coins",
          type: "windfall",
          bonusMinorUnits: 500,
        },
      },
      {
        id: "w5",
        incomeMinorUnits: 500,
        event: {
          id: "goal-check",
          type: "milestone",
        },
      },
    ],
  },
  {
    key: "builder-standard",
    ageBand: "builder",
    difficulty: "standard",
    startingBalanceMinorUnits: 500,
    savingsGoalTargetMinorUnits: 2500,
    xpReward: 35,
    coinRewardMinorUnits: 700,
    estimatedMinutes: 4,
    weeks: [
      {
        id: "w1",
        incomeMinorUnits: 1500,
      },
      {
        id: "w2",
        incomeMinorUnits: 1500,
        event: {
          id: "phone-case",
          type: "expense",
          costMinorUnits: 600,
        },
      },
      {
        id: "w3",
        incomeMinorUnits: 1500,
        event: {
          id: "concert-tickets",
          type: "opportunity",
          choices: [
            { key: "go", category: "wants", costMinorUnits: 1200 },
            { key: "skip", category: "wants", costMinorUnits: 0 },
          ],
        },
      },
      {
        id: "w4",
        incomeMinorUnits: 1000,
        event: {
          id: "goal-check",
          type: "milestone",
        },
      },
    ],
  },
  {
    key: "strategist-standard",
    ageBand: "strategist",
    difficulty: "standard",
    startingBalanceMinorUnits: 1000,
    savingsGoalTargetMinorUnits: 8000,
    xpReward: 40,
    coinRewardMinorUnits: 900,
    estimatedMinutes: 5,
    weeks: [
      {
        id: "w1",
        incomeMinorUnits: 3000,
      },
      {
        id: "w2",
        incomeMinorUnits: 3000,
        event: {
          id: "subscription-renewal",
          type: "expense",
          costMinorUnits: 900,
        },
      },
      {
        id: "w3",
        incomeMinorUnits: 3000,
        event: {
          id: "limited-offer",
          type: "opportunity",
          choices: [
            { key: "take", category: "wants", costMinorUnits: 2000 },
            { key: "wait", category: "wants", costMinorUnits: 0 },
          ],
        },
      },
      {
        id: "w4",
        incomeMinorUnits: 3000,
        event: {
          id: "freelance-bonus",
          type: "windfall",
          bonusMinorUnits: 1500,
        },
      },
      {
        id: "w5",
        incomeMinorUnits: 2000,
        event: {
          id: "goal-check",
          type: "milestone",
        },
      },
    ],
  },
];
