-- Money Quest — 0005_seed_games.sql
-- Generated by scripts/generate-game-seed-sql.ts directly from the real
-- game-engine configs (src/game-engine/configs/) — do not hand-edit the
-- generated rows; edit the config and regenerate instead, so the database
-- and the actual game content can never drift apart.

insert into public.activities
  (id, world_id, topic_id, age_band, level, activity_type, title, learning_objective, content, xp_reward, coin_reward_minor_units, order_index)
values
  ('game-explorer-needs-or-wants', 'market-town', 'needs_wants', 'explorer', 1, 'game', 'Needs or Wants?', 'Sort everyday items into needs and wants.', '{"engineType":"game","gameKey":"needs-or-wants"}'::jsonb, 15, 300, 1),
  ('game-builder-needs-or-wants', 'market-town', 'needs_wants', 'builder', 1, 'game', 'Needs or Wants?', 'Sort everyday items into needs and wants.', '{"engineType":"game","gameKey":"needs-or-wants"}'::jsonb, 20, 400, 2),
  ('game-strategist-needs-or-wants', 'market-town', 'needs_wants', 'strategist', 1, 'game', 'Needs or Wants?', 'Sort everyday items into needs and wants.', '{"engineType":"game","gameKey":"needs-or-wants"}'::jsonb, 25, 500, 3),
  ('game-explorer-save-or-spend', 'golden-vault', 'saving', 'explorer', 1, 'game', 'Save or Spend?', 'Decide whether each choice is saving or spending.', '{"engineType":"game","gameKey":"save-or-spend"}'::jsonb, 15, 300, 4),
  ('game-explorer-build-a-budget', 'golden-vault', 'budgeting', 'explorer', 1, 'game', 'Build a Budget', 'Split a fixed amount of coins across spending, saving, and giving.', '{"engineType":"game","gameKey":"build-a-budget"}'::jsonb, 20, 400, 5),
  ('game-explorer-smart-shopper', 'market-town', 'smart_shopping', 'explorer', 1, 'game', 'Smart Shopper', 'Pick the better-value option between similar items.', '{"engineType":"game","gameKey":"smart-shopper"}'::jsonb, 15, 300, 6),
  ('game-explorer-price-detective', 'market-town', 'comparing_prices', 'explorer', 1, 'game', 'Price Detective', 'Compare prices to find the genuinely cheaper option.', '{"engineType":"game","gameKey":"price-detective"}'::jsonb, 15, 300, 7),
  ('game-explorer-reach-your-goal', 'golden-vault', 'financial_goals', 'explorer', 1, 'game', 'Reach Your Goal', 'Work out what it takes to reach a savings goal.', '{"engineType":"game","gameKey":"reach-your-goal"}'::jsonb, 20, 400, 8),
  ('game-explorer-earn-your-coins', 'coin-cove', 'earning', 'explorer', 1, 'game', 'Earn Your Coins', 'Match jobs and chores to how they earn money.', '{"engineType":"game","gameKey":"earn-your-coins"}'::jsonb, 15, 300, 9),
  ('game-explorer-bank-builder', 'golden-vault', 'banking', 'explorer', 1, 'game', 'Bank Builder', 'Calculate a running balance after deposits.', '{"engineType":"game","gameKey":"bank-builder"}'::jsonb, 15, 300, 10),
  ('game-explorer-interest-grower', 'golden-vault', 'interest', 'explorer', 1, 'game', 'Interest Grower', 'Work out how saved coins can grow with interest.', '{"engineType":"game","gameKey":"interest-grower"}'::jsonb, 15, 300, 11),
  ('game-explorer-money-choices', 'horizon-peaks', 'decision_making', 'explorer', 1, 'game', 'Money Choices', 'Practice thinking through everyday money decisions.', '{"engineType":"game","gameKey":"money-choices"}'::jsonb, 15, 300, 12),
  ('game-explorer-currency-explorer', 'sky-exchange', 'currencies', 'explorer', 1, 'game', 'Currency Explorer', 'Match currency symbols and countries from around the world.', '{"engineType":"game","gameKey":"currency-explorer"}'::jsonb, 15, 300, 13),
  ('game-explorer-scam-detective', 'guardian-gate', 'scams', 'explorer', 1, 'game', 'Scam Detective', 'Spot the warning signs in a suspicious message.', '{"engineType":"game","gameKey":"scam-detective"}'::jsonb, 15, 300, 14);
