-- Money Quest — 0006_seed_simulator.sql
-- Generated by scripts/generate-simulator-seed-sql.ts directly from the real
-- simulator scenario configs (src/simulator/scenarios/) — do not hand-edit;
-- edit the scenario and regenerate instead.

insert into public.activities
  (id, world_id, topic_id, age_band, level, activity_type, title, learning_objective, content, xp_reward, coin_reward_minor_units, order_index)
values
  ('sim-explorer-standard', 'horizon-peaks', 'decision_making', 'explorer', 1, 'challenge', 'A Month of Weekly Coins', 'Manage fictional weekly income across needs, wants, savings, and giving toward: A new kite.', '{"engineType":"simulator","scenarioKey":"explorer-standard"}'::jsonb, 30, 600, 100),
  ('sim-explorer-challenge', 'horizon-peaks', 'decision_making', 'explorer', 1, 'challenge', 'A Bigger Month of Choices', 'Manage fictional weekly income across needs, wants, savings, and giving toward: A new bike helmet.', '{"engineType":"simulator","scenarioKey":"explorer-challenge"}'::jsonb, 40, 800, 101),
  ('sim-builder-standard', 'horizon-peaks', 'decision_making', 'builder', 1, 'challenge', 'Managing a Month of Allowance', 'Manage fictional weekly income across needs, wants, savings, and giving toward: A new game console accessory.', '{"engineType":"simulator","scenarioKey":"builder-standard"}'::jsonb, 35, 700, 102),
  ('sim-strategist-standard', 'horizon-peaks', 'decision_making', 'strategist', 1, 'challenge', 'Your First Part-Time Earnings', 'Manage fictional weekly income across needs, wants, savings, and giving toward: Savings toward a laptop upgrade.', '{"engineType":"simulator","scenarioKey":"strategist-standard"}'::jsonb, 40, 900, 103);
