extends Node3D
## WorldHub — the plaza connecting all 7 Money Quest World destinations
## (see docs/money-quest-world-architecture.md Section 2). Not a menu with
## seven buttons: a real place the player walks around — a central coin
## fountain, a ring promenade, district-coloured paths out to seven
## distinct landmark buildings (each entered through a glowing arch where
## its Portal* node sits), a fingerpost at spawn, and a Hub Guide NPC who
## explains the place in two short lines instead of a wall of text (per
## the brief's "the child should understand where each destination leads
## without needing to read large amounts of text").
##
## The scenery is generated by HubLandscape, SignPost and the Landmark
## scenes from the portals' positions; the Portal* nodes themselves remain
## the navigation contract (PortalInteraction, label_key, target_zone_id).

@onready var player: Node3D = $Player
@onready var camera_controller: CameraController = $CameraController
@onready var hub_guide: NPC = $HubGuide


func _ready() -> void:
	camera_controller.target = player
	hub_guide.talked_to.connect(_on_hub_guide_talked_to)


func _on_hub_guide_talked_to(_npc_id: String) -> void:
	await DialogueBox.show_text("hub.guide.welcome_line1")
	await DialogueBox.show_text("hub.guide.welcome_line2")
